#!/bin/sh


text1="
func fucntion(){


}

print('worked')



"



if [  "$1" == "-n"  ]; then
	echo "$text1"
fi




while getopts ":h" option; do 
	case $option in
	h) echo 'type pyfill -n and it will echo the basic python code for a start up project'
	exit;;
esac
done

